#Window
hide_window_decorations yes

remember_window_size no
initial_window_width 120c
initial_window_height 32c

window_padding_width 10
window_margin_width 0

# Font
#font_family Cascadia Code PL
font_size 11.0

#Transparency
background_opacity 0.70
background_blur 30


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME